"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or ('local-development-only-not-for-production' if DEBUG else '')
if not SECRET_KEY:
    raise RuntimeError('DJANGO_SECRET_KEY must be configured when DJANGO_DEBUG is false.')

default_allowed_hosts = '127.0.0.1,localhost,.trycloudflare.com' if DEBUG else '127.0.0.1,localhost'
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', default_allowed_hosts).split(',')
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ['https://*.trycloudflare.com']
if not DEBUG:
    if not ALLOWED_HOSTS:
        raise RuntimeError('DJANGO_ALLOWED_HOSTS must be configured when DJANGO_DEBUG is false.')
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError('DJANGO_CSRF_TRUSTED_ORIGINS must be configured when DJANGO_DEBUG is false.')
    if not os.environ.get('DATABASE_URL', '').strip():
        raise RuntimeError('DATABASE_URL must point to a durable production database.')
    if not os.environ.get('DJANGO_MEDIA_ROOT', '').strip():
        raise RuntimeError('DJANGO_MEDIA_ROOT must point to persistent media storage in production.')

CACHE_BACKEND = os.environ.get('DJANGO_CACHE_BACKEND', '').strip()
CACHE_LOCATION = os.environ.get('DJANGO_CACHE_LOCATION', '').strip()
if not DEBUG:
    CACHE_BACKEND = CACHE_BACKEND or 'django.core.cache.backends.filebased.FileBasedCache'
    CACHE_LOCATION = CACHE_LOCATION or str(BASE_DIR / '.cache')
if CACHE_BACKEND and CACHE_LOCATION:
    CACHES = {
        'default': {
            'BACKEND': CACHE_BACKEND,
            'LOCATION': CACHE_LOCATION,
        }
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'learning.apps.LearningConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL:
    database_options = {
        'conn_max_age': 600,
        'conn_health_checks': True,
    }
    if not DATABASE_URL.lower().startswith('sqlite://'):
        database_options['ssl_require'] = not DEBUG
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            **database_options,
        )
    }
else:
    DATABASE_NAME = os.environ.get('DJANGO_DB_NAME') or BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATABASE_NAME,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        )
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'FDE-AI 學習平台 <no-reply@example.invalid>')

PUBLIC_RAG_UPSTREAM_URL = os.environ.get(
    'DJANGO_PUBLIC_RAG_UPSTREAM_URL',
    'http://127.0.0.1:8770' if DEBUG else '',
).strip()
PUBLIC_INSPECTION_UPSTREAM_URL = os.environ.get(
    'DJANGO_PUBLIC_INSPECTION_UPSTREAM_URL',
    'http://127.0.0.1:8765' if DEBUG else '',
).strip()
PUBLIC_VOICE_UPSTREAM_URL = os.environ.get(
    'DJANGO_PUBLIC_VOICE_UPSTREAM_URL', PUBLIC_INSPECTION_UPSTREAM_URL,
).strip()
PUBLIC_AI_TIMEOUT_SECONDS = max(1, int(os.environ.get('DJANGO_PUBLIC_AI_TIMEOUT_SECONDS', '20')))
PUBLIC_AI_MAX_REQUEST_BYTES = max(1024, int(os.environ.get('DJANGO_PUBLIC_AI_MAX_REQUEST_BYTES', '25000000')))
PUBLIC_RAG_REQUESTS_PER_MINUTE = max(1, int(os.environ.get('DJANGO_PUBLIC_RAG_REQUESTS_PER_MINUTE', '30')))
PUBLIC_INSPECTION_REQUESTS_PER_MINUTE = max(1, int(os.environ.get('DJANGO_PUBLIC_INSPECTION_REQUESTS_PER_MINUTE', '5')))
PUBLIC_VOICE_REQUESTS_PER_MINUTE = max(1, int(os.environ.get('DJANGO_PUBLIC_VOICE_REQUESTS_PER_MINUTE', '20')))
PUBLIC_AI_TRUSTED_PROXY_IPS = frozenset(
    ip.strip()
    for ip in os.environ.get('DJANGO_PUBLIC_AI_TRUSTED_PROXY_IPS', '').split(',')
    if ip.strip()
)

MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or BASE_DIR / 'private_media')
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_500_000
GROWTH_VIDEO_MAX_UPLOAD_BYTES = int(
    os.environ.get('DJANGO_GROWTH_VIDEO_MAX_UPLOAD_BYTES', str(300 * 1024 * 1024))
)
GROWTH_VIDEO_MAX_DURATION_SECONDS = 30
GROWTH_VIDEO_MAX_FPS = 30
GROWTH_VIDEO_CRF = 28
GROWTH_VIDEO_PRESET = os.environ.get('DJANGO_GROWTH_VIDEO_PRESET', 'veryfast')
GROWTH_VIDEO_FFMPEG_BINARY = os.environ.get('DJANGO_FFMPEG_BINARY', 'ffmpeg')
GROWTH_VIDEO_FFPROBE_BINARY = os.environ.get('DJANGO_FFPROBE_BINARY', 'ffprobe')
# Keep enough multipart headroom for the 300 MB raw video limit. Large files
# still use Django's temporary-file upload handler because the memory limit
# above remains 2.5 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = max(
    int(os.environ.get('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', '0') or 0),
    GROWTH_VIDEO_MAX_UPLOAD_BYTES + 2_000_000,
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'false').lower() == 'true'
SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'false').lower() == 'true'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {
        'django': {'handlers': ['console'], 'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')},
        'learning': {'handlers': ['console'], 'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'), 'propagate': False},
    },
}
