# Generated by Django 5.2.17 on 2026-09-14 06:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('cohort_id', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', '班級編號格式須為 YYYY-期別。')])),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cohort_id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', '圖片'), ('video', '影片'), ('file', '檔案'), ('github', 'GitHub'), ('model', '模型權重'), ('survey', '測繪成果'), ('3d', '3D 作品'), ('other', '其他')], max_length=12)),
                ('external_url', models.URLField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to=learning.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'pdf', 'zip', 'pt', 'onnx', 'tif', 'tiff', 'obj', 'stl', 'glb', 'txt']), learning.models.validate_evidence_size])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_to_dataset', models.BooleanField(default=False)),
                ('promote_to_rag', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_candidates', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_record', to='learning.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='學員 ID 格式須為 YYYY-期別-S編號，例如 2026-01-S01。', regex='^\\d{4}-\\d{2}-S\\d{2,}$')])),
                ('legal_name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=40)),
                ('expected_email', models.EmailField(blank=True, max_length=254)),
                ('github_repo_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='learning.cohort')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('submitted', '已提交'), ('reviewed', '教師已複核'), ('incomplete', '未完成'), ('skipped', '跳過')], default='not_started', max_length=16)),
                ('task_version_snapshot', models.PositiveSmallIntegerField(default=1)),
                ('student_note', models.TextField(blank=True)),
                ('teacher_note', models.TextField(blank=True)),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skipped_reason', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='learning.studentprofile')),
            ],
            options={
                'ordering': ['task__sort_order', 'task__task_id'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.studenttaskprogress'),
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('task_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(choices=[('learn', '學'), ('practice', '練'), ('build', '做'), ('assess', '測'), ('certify', '證')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('evidence_required', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_task_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'task_id'],
            },
        ),
        migrations.AddField(
            model_name='studenttaskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='learning.taskdefinition'),
        ),
        migrations.CreateModel(
            name='TeacherReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('reviewed', '教師已複核'), ('incomplete', '未完成'), ('skipped', '跳過')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_events', to='learning.evidence')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='learning.studenttaskprogress')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('learn', '學'), ('practice', '練'), ('build', '做'), ('assess', '測'), ('certify', '證')], max_length=12)),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('completed', '已完成'), ('skipped', '跳過')], default='not_started', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_progress', to='learning.studentprofile')),
            ],
            options={
                'ordering': ['phase'],
                'constraints': [models.UniqueConstraint(fields=('student', 'phase'), name='one_phase_per_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='studenttaskprogress',
            constraint=models.UniqueConstraint(fields=('student', 'task'), name='one_progress_per_student_task'),
        ),
    ]
