# Generated by Django 5.2.17 on 2026-09-14 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinitionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(choices=[('learn', '學'), ('practice', '練'), ('build', '做'), ('assess', '測'), ('certify', '證')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('evidence_required', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='learning.taskdefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_definition_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task__task_id', '-version'],
                'constraints': [models.UniqueConstraint(fields=('task', 'version'), name='one_revision_per_task_version')],
            },
        ),
    ]
