# Generated by Django 5.2.17 on 2026-09-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_taskdefinitionrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCohortAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_accesses', to='learning.cohort')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cohort_id', 'teacher__username'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'cohort'), name='one_teacher_access_per_cohort')],
            },
        ),
    ]
