# Generated by Django 5.2.17 on 2026-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_teachercohortaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registered_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
