# Generated by Django 5.2.17 on 2026-09-14 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_anonymous_accounts_and_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cohort_id', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='evidence',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.studenttaskprogress'),
        ),
        migrations.CreateModel(
            name='GrowthRecordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^R0[1-8]$')])),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('completion_requirements', models.JSONField(blank=True, default=list)),
                ('evidence_requirement', models.JSONField(blank=True, default=list)),
                ('learning_resource', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_record_definitions', to='learning.cohort')),
            ],
            options={
                'ordering': ['display_order', 'slot_id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecordSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('submitted', '已提交'), ('needs_revision', '需要補充'), ('approved', '合格'), ('rejected', '不合格')], default='not_started', max_length=16)),
                ('student_note', models.TextField(blank=True)),
                ('learning_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.growthrecorddefinition')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_submissions', to='learning.enrollment')),
                ('selected_evidence', models.ManyToManyField(blank=True, related_name='summary_submissions', to='learning.evidence')),
            ],
            options={
                'ordering': ['definition__display_order', 'definition__slot_id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecordReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('approved', '合格'), ('needs_revision', '需要補充'), ('rejected', '不合格')], max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('teacher_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_record_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.growthrecordsubmission')),
            ],
            options={
                'ordering': ['-reviewed_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='growth_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.growthrecordsubmission'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('growth_submission__isnull', True), ('progress__isnull', False)), models.Q(('growth_submission__isnull', False), ('progress__isnull', True)), _connector='OR'), name='evidence_has_exactly_one_parent'),
        ),
        migrations.AddField(
            model_name='learninggroup',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='growthrecorddefinition',
            name='group_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_record_definitions', to='learning.learninggroup'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='learning.learninggroup'),
        ),
        migrations.AddConstraint(
            model_name='growthrecordsubmission',
            constraint=models.UniqueConstraint(fields=('enrollment', 'definition'), name='one_growth_submission_per_record'),
        ),
        migrations.AddConstraint(
            model_name='growthrecordreview',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='growth_review_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='learninggroup',
            constraint=models.UniqueConstraint(fields=('cohort', 'code'), name='one_group_code_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='growthrecorddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('group_scope__isnull', True)), fields=('cohort', 'slot_id'), name='one_default_growth_definition_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='growthrecorddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('group_scope__isnull', False)), fields=('cohort', 'slot_id', 'group_scope'), name='one_group_growth_definition_per_slot'),
        ),
    ]
