# Generated by Django 5.2.17 on 2026-09-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_growth_records_v15b'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='original_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='processed_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
