# Generated by Django 5.2.17 on 2026-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_growth_evidence_metadata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='growthrecordsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('teacher_final_score__isnull', True), models.Q(('teacher_final_score__gte', 0), ('teacher_final_score__lte', 100)), _connector='OR'), name='growth_final_score_0_100'),
        ),
    ]
