# Generated by Django 5.2.17 on 2026-09-15 03:38

import django.core.validators
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_growth_final_score_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='upload',
            field=models.FileField(blank=True, upload_to=learning.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'pdf', 'ppt', 'pptx', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'zip', 'pt', 'onnx', 'tif', 'tiff', 'obj', 'stl', 'glb', 'txt', 'odt', 'odp', 'ods']), learning.models.validate_evidence_size]),
        ),
    ]
