# Generated by Django 5.2.17 on 2026-09-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_evidence_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='project_direction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
