# Generated by Django 5.2.17 on 2026-09-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_enrollment_project_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='teacher_verified',
            field=models.BooleanField(default=False),
        ),
    ]
