# Generated by Django 5.2.17 on 2026-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_enrollment_teacher_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='teacher_verified_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
