# Generated by Django 5.2.17 on 2026-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_enrollment_teacher_verified_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='training_source',
            field=models.CharField(blank=True, choices=[('pre_employment', '職前培訓'), ('in_service', '在職培訓'), ('college', '大中專院校'), ('other', '其他')], max_length=20, null=True),
        ),
    ]
