# Generated by Django 5.2.17 on 2026-09-22 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_enrollment_training_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a01', models.PositiveSmallIntegerField()),
                ('a02', models.PositiveSmallIntegerField()),
                ('a03', models.PositiveSmallIntegerField()),
                ('a04', models.PositiveSmallIntegerField()),
                ('a05', models.PositiveSmallIntegerField()),
                ('a06', models.PositiveSmallIntegerField()),
                ('a07', models.PositiveSmallIntegerField()),
                ('helpful_topics', models.JSONField(blank=True, default=list)),
                ('helpful_other', models.CharField(blank=True, max_length=100)),
                ('future_interests', models.JSONField(blank=True, default=list)),
                ('path_20_interest', models.CharField(blank=True, choices=[('very_interested', '非常有興趣'), ('interested', '有興趣'), ('learn_more', '想先了解'), ('not_now', '目前沒有')], max_length=20)),
                ('path_25_interest', models.CharField(blank=True, choices=[('very_interested', '非常有興趣'), ('interested', '有興趣'), ('learn_more', '想先了解'), ('not_now', '目前沒有')], max_length=20)),
                ('path_30_interest', models.CharField(blank=True, choices=[('very_interested', '非常有興趣'), ('interested', '有興趣'), ('learn_more', '想先了解'), ('not_now', '目前沒有')], max_length=20)),
                ('license_interest', models.JSONField(blank=True, default=list)),
                ('course_format_preferences', models.JSONField(blank=True, default=list)),
                ('course_duration_preference', models.CharField(blank=True, max_length=32)),
                ('course_priority_factors', models.JSONField(blank=True, default=list)),
                ('advanced_course_intent', models.CharField(blank=True, choices=[('HIGH', '很有意願參加'), ('INTERESTED', '有意願，想先了解課程內容與費用'), ('TIME_UNCERTAIN', '有興趣，但目前時間還不確定'), ('INFO_ONLY', '目前只想先收到相關資訊'), ('NONE', '暫時沒有進階學習計畫')], max_length=20)),
                ('contact_opt_in', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('next_step_text', models.CharField(blank=True, max_length=300)),
                ('feedback_text', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_surveys', to='learning.enrollment')),
                ('growth_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_survey', to='learning.growthrecordsubmission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='learning.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment',), name='one_student_survey_per_enrollment')],
            },
        ),
    ]
