# Generated by Django 5.2.17 on 2026-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_student_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsurvey',
            name='survey_version',
            field=models.CharField(default='v1', max_length=8),
        ),
        migrations.AddField(
            model_name='studentsurvey',
            name='v2_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
